spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true$serverTimezone=UTC
    username: root
    password: vova
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

  liquibase.change-log:
    classpath:liquibase-changeLog.xml

  data:
    web:
      pageable:
        default-page-size: 25
        max-page-size: 100
server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org:
      springframework:
        web=INFO:

